apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shahd
  template:
    metadata:
      name: my-web-pod
      labels:
        app: shahd
    spec:
      containers:
        - image: shahdlu/pro
          name: custom-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80